FROM applatix/tomcat-postgres  
MAINTAINER dinar@applatix.com


# RUN echo "export JAVA_OPTS=\"-Dapp.env=dev\"" > /usr/local/tomcat/bin/setenv.sh  
#COPY m3-java-capstone-1.0.war /opt/tomcat/webapps/m3-java-capstone-1.0.war 

#CMD ["/bin/run.sh"]
# CMD ["/opt/tomcat/bin/catalina.sh", "run"]  